config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :admin_devices
  root 'home#index'
  resources :devices
  devise_for :users
end

app/models/device.rb
class Device < ApplicationRecord
	validates :dispid, uniqueness: true, presence: true, length: {minimum:10, maximum: 10}
	validate :validate_dev_id
	before_update :validate_dev_id
	belongs_to :user

	def validate_dev_id
		if AdminDevice.where(serial: self.dispid).exists?
			return
		else
			errors.add(:device, 'invalid ID')
		end
	end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

	def new
		@device = Device.new
	end

	def edit
		@device = Device.find(params[:id])
	end

	def create
		@device = Device.new(device_params)
		@user = current_user
		@device.admin_device_id = AdminDevice.where(serial: @device.dispid).first&.id
		@device.user_id = current_user.id
		@user.device = @device.id #related to has_one at model
		if @device.save #first validate new device coudl be saved
			if @user.save #then validate user coud be saved
				#done in nested ifs to avoid saving failure at one save causing other save to be done either way
				#TODO: send SMS to device using dispid
				redirect_to edit_user_registration_path
				else
					render 'new'
				end
		else
			render 'new'
		end
	end

	def update
		@device = Device.find(params[:id])
		@device.admin_device_id = AdminDevice.where(serial: device_params[:dispid]).first&.id
		if @device.update(device_params)
			redirect_to edit_user_registration_path
		else
			render 'edit'
		end
	end

	private
		def device_params
			params.require(:device).permit(:dispid)
		end

end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/edit.html.haml
/ Content Row
.row
  Update the ID of your registered device
  - if @device.errors.any?
    #error_explanation
    %h2
    = pluralize(@device.errors.count, "error")
    prohibited this device from being updated:
    %ul
    - @device.errors.full_messages.each do |message|
      %li= message
  %br
  = form_with(model: @device, local: true) do |f|
    = f.text_field :dispid
    = f.submit 'Update'

app/views/devices/new.html.haml
/ Content Row
.row
  .col-lg-3.col-md-6.text-center
    %h3.h4.mb-2 Register your device
    - if @device.errors.any?
      #error_explanation
      = pluralize(@device.errors.count, "error")
      prohibited this device from being saved:
      %ul
    - @device.errors.full_messages.each do |message|
      %li= message
    = form_with scope: :device, url: devices_path, local: true do |f|
      %p
      = f.text_field :dispid
      %br/
      %p
        = f.submit 'Register'