config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :admin_devices
  root 'home#index'
  resources :devices
  devise_for :users
end

app/views/landing/_home_logged.html.haml
/ Content Row
.row
  / Device Id Card
  .col-xl-3.col-md-6.mb-4
    .card.border-left-primary.shadow.h-100.py-2
      .card-body
        .row.no-gutters.align-items-center
          .col.mr-2
            .text-xs.font-weight-bold.text-primary.text-uppercase.mb-1 your device
            - if !current_user.device.nil?
              .h5.mb-0.font-weight-bold.text-gray-800= current_user.device.dispid
            - else
              .h5.mb-0.font-weight-bold.text-gray-800 No device assigned!
          .col-auto
            %i.fas.fa-key.fa-2x.text-gray-300

  / Admin Card
  .col-xl-3.col-md-6.mb-4
    .card.border-left-success.shadow.h-100.py-2
      .card-body
        .row.no-gutters.align-items-center
          .col.mr-2
            .text-xs.font-weight-bold.text-success.text-uppercase.mb-1 Are you admin?
            .h5.mb-0.font-weight-bold.text-gray-800= current_user.admin
          .col-auto
            %i.fas.fa-user-shield.fa-2x.text-gray-300
  / Placeholder 1
  .col-xl-3.col-md-6.mb-4
    .card.border-left-info.shadow.h-100.py-2
      .card-body
        .row.no-gutters.align-items-center
          .col.mr-2
            .text-xs.font-weight-bold.text-info.text-uppercase.mb-1 Tasks
            .row.no-gutters.align-items-center
              .col-auto
                .h5.mb-0.mr-3.font-weight-bold.text-gray-800 0%
              .col
                .progress.progress-sm.mr-2
                  .progress-bar.bg-info{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "0", :role => "progressbar", :style => "width: 0%"}
          .col-auto
            %i.fas.fa-clipboard-list.fa-2x.text-gray-300
  / Pending Requests Card Example
  .col-xl-3.col-md-6.mb-4
    .card.border-left-warning.shadow.h-100.py-2
      .card-body
        .row.no-gutters.align-items-center
          .col.mr-2
            .text-xs.font-weight-bold.text-warning.text-uppercase.mb-1 Pending Requests
            .h5.mb-0.font-weight-bold.text-gray-800 0
          .col-auto
            %i.fas.fa-comments.fa-2x.text-gray-300
/ Content Row
.row
  / Content Column
  .col-lg-6.mb-4
    / Project Card Example
    .card.shadow.mb-4
      .card-header.py-3
        %h6.m-0.font-weight-bold.text-primary Projects
      .card-body
        %h4.small.font-weight-bold
          Devices registered
          %span.float-right 0%
        .progress.mb-4
          .progress-bar.bg-danger{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "0", :role => "progressbar", :style => "width: 0%"}
        %h4.small.font-weight-bold
          Users contacts
          %span.float-right 0%
        .progress.mb-4
          .progress-bar.bg-warning{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "0", :role => "progressbar", :style => "width: 0%"}
    / Color System
    .row
      .col-lg-6.mb-4
        .card.bg-primary.text-white.shadow
          .card-body
            Primary
            .text-white-50.small #4e73df
      .col-lg-6.mb-4
        .card.bg-success.text-white.shadow
          .card-body
            Success
            .text-white-50.small #1cc88a
      .col-lg-6.mb-4
        .card.bg-info.text-white.shadow
          .card-body
            Info
            .text-white-50.small #36b9cc
      .col-lg-6.mb-4
        .card.bg-warning.text-white.shadow
          .card-body
            Warning
            .text-white-50.small #f6c23e
      .col-lg-6.mb-4
        .card.bg-danger.text-white.shadow
          .card-body
            Danger
            .text-white-50.small #e74a3b
      .col-lg-6.mb-4
        .card.bg-secondary.text-white.shadow
          .card-body
            Secondary
            .text-white-50.small #858796
  .col-lg-6.mb-4
    / Illustrations
    .card.shadow.mb-4
      .card-header.py-3
        %h6.m-0.font-weight-bold.text-primary Illustrations
      .card-body
        %p
          Aqui puedes poner mas informacion 
    / Approach
    .card.shadow.mb-4
      .card-header.py-3
        %h6.m-0.font-weight-bold.text-primary Development Approach
      .card-body
        %p solo informacion que poner aqui?
        %p.mb-0 algo mas de information 

app/views/landing/_home_not_logged.html.haml
%body#page-top
  / Navigation
  %nav#mainNav.navbar.navbar-expand-lg.navbar-light.fixed-top.py-3
    .container
      %a.navbar-brand.js-scroll-trigger{:href => "#page-top"} Start
      %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarResponsive.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto.my-2.my-lg-0
          %li.nav-item
            %a.nav-link.js-scroll-trigger{:href => "#"} About
          %li.nav-item
            %a.nav-link.js-scroll-trigger{:href => "#"} Contact
          %li.nav-item
            %a.nav-link.js-scroll-trigger{:href => new_user_session_path} Log In

  / Masthead
  %header.masthead
    .container.h-100
      .row.h-100.align-items-center.justify-content-center.text-center
        .col-lg-10.align-self-end
          %h1.text-uppercase.text-white.font-weight-bold Your Favorite Source of Free Bootstrap Themes
        .col-lg-8.align-self-baseline
          %p.text-white-75.font-weight-light.mb-5 Start your device administration
          %a.btn.btn-primary.btn-xl.js-scroll-trigger{:href => new_user_registration_path} Sign Up

  / Services section
  %section#services.page-section
    .container
      .row
        .col-lg-3.col-md-6.text-center
          .mt-5
            %i.fas.fa-4x.fa-gem.text-primary.mb-4
            %h3.h4.mb-2 Sturdy Themes
            %p.text-muted.mb-0 Our themes are updated regularly to keep them bug free!
        .col-lg-3.col-md-6.text-center
          .mt-5
            %i.fas.fa-4x.fa-laptop-code.text-primary.mb-4
            %h3.h4.mb-2 Up to Date
            %p.text-muted.mb-0 All dependencies are kept current to keep things fresh.
        .col-lg-3.col-md-6.text-center
          .mt-5
            %i.fas.fa-4x.fa-globe.text-primary.mb-4
            %h3.h4.mb-2 Ready to Publish
            %p.text-muted.mb-0 You can use this design as is, or you can make changes!
        .col-lg-3.col-md-6.text-center
          .mt-5
            %i.fas.fa-4x.fa-heart.text-primary.mb-4
            %h3.h4.mb-2 Made with Love
            %p.text-muted.mb-0 Is it really open source if its not made with love?
      %hr.divider.my-4/
  %header.masthead
    .container.h-100
      .row.h-100.align-items-center.justify-content-center.text-center
        .col-lg-4.ml-auto.text-center.mb-5.mb-lg-0
          %i.fas.fa-phone.fa-3x.mb-3.text-muted
          %div +52 656 136 00 85
        .col-lg-4.mr-auto.text-center
          %i.fas.fa-envelope.fa-3x.mb-3.text-muted
          / Make sure to change the email address in BOTH the anchor text and the link target below!
          %a.d-block{:href => "mailto:contact@yourwebsite.com"} contact@app.com
  / Footer
  %footer.bg-light.py-5
    .container
      .small.text-center.text-muted Copyright © 2020 - Start ChoDav

app/views/landing/original_home_not_logged.html.haml
%h1 Homepage
- if current_user
  %p
    Signed in as: #{current_user.email}
  = link_to   'Profile', edit_user_registration_path, method: :get
  - if current_user.device.nil?
    = link_to 'Register your device', new_device_path, method: :get
  = button_to 'Log out', destroy_user_session_path, method: :delete
  - if current_user.admin
    = link_to 'admin_devices', admin_devices_path
- else
  = button_to 'Register', new_user_registration_path, method: :get
  = button_to 'Log in', new_user_session_path, method: :get