config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :admin_devices
  root 'home#index'
  resources :devices
  devise_for :users
end

app/models/admin_device.rb
class AdminDevice < ApplicationRecord
	validates :serial, numericality: true, uniqueness: true, presence: true, length: {minimum:10, maximum: 10}
end

app/controllers/admin_devices_controller.rb
class AdminDevicesController < ApplicationController
  before_action :set_admin_device, only: [:show, :edit, :update, :destroy]
  before_action :check_admin

  # GET /admin_devices
  # GET /admin_devices.json
  def index
    @admin_devices = AdminDevice.all
  end

  # GET /admin_devices/1
  # GET /admin_devices/1.json
  def show
  end

  # GET /admin_devices/new
  def new
    @admin_device = AdminDevice.new
  end

  # GET /admin_devices/1/edit
  def edit
  end

  # POST /admin_devices
  # POST /admin_devices.json
  def create
    @admin_device = AdminDevice.new(admin_device_params)

    respond_to do |format|
      if @admin_device.save
        format.html { redirect_to @admin_device, notice: 'Admin device was successfully created.' }
        format.json { render :show, status: :created, location: @admin_device }
      else
        format.html { render :new }
        format.json { render json: @admin_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_devices/1
  # PATCH/PUT /admin_devices/1.json
  def update
    respond_to do |format|
      if @admin_device.update(admin_device_params)
        format.html { redirect_to @admin_device, notice: 'Admin device was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_device }
      else
        format.html { render :edit }
        format.json { render json: @admin_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_devices/1
  # DELETE /admin_devices/1.json
  def destroy
    #FIXME check if admin device is associated with a user to update the user info
    @admin_device.destroy
    respond_to do |format|
      format.html { redirect_to admin_devices_url, notice: 'Admin device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_device
      @admin_device = AdminDevice.find(params[:id])
    end

    def check_admin
      if current_user && current_user.admin
        return
      else
        redirect_to root_path, alert: 'You are not an admin'
      end
    end

    # Only allow a list of trusted parameters through.
    def admin_device_params
      params.require(:admin_device).permit(:serial)
    end
end

app/helpers/admin_devices_helper.rb
module AdminDevicesHelper
end

app/views/admin_devices/_form.html.haml
= form_with(model: admin_device, local: true) do |form|
  - if admin_device.errors.any?
    #error_explanation
      %h2
        = pluralize(admin_device.errors.count, "error")
        prohibited this admin_device from being saved:
      %ul
        - admin_device.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :serial
    = form.text_field :serial
  .actions
    = form.submit

app/views/admin_devices/edit.html.haml
/ Content Row
.row
  Editing Admin Device
  = render 'form', admin_device: @admin_device
  %br
  %br
%p
  = link_to 'Show', @admin_device
  |
  = link_to 'Back', admin_devices_path

app/views/admin_devices/index.html.haml
/ Content Row
.row
  %p#notice= notice
  %h1 Admin Devices
  %table.table
    %thead
      %tr
        %th Serial
        %th{:colspan => "3"}
          %tbody
        - @admin_devices.each do |admin_device|
          %tr
          %td= admin_device.serial
          %td= link_to 'Show', admin_device
          %td= link_to 'Edit', edit_admin_device_path(admin_device)
          %td= link_to 'Destroy', admin_device, method: :delete, data: { confirm: 'Are you sure?' }
          %br/
  = link_to 'New Admin Device', new_admin_device_path

app/views/admin_devices/new.html.haml
/ Content Row
.row
  .col-lg-3.col-md-6.text-center
    %h3.h4.mb-2 Admin Device
    = render 'form', admin_device: @admin_device
    %br
    = link_to 'Back', admin_devices_path

app/views/admin_devices/show.html.haml
/ Content Row
.row
  .col-lg-3.col-md-6.text-center
    %p#notice= notice
    %p
      %strong Serial:
      = @admin_device.serial
      = link_to 'Edit', edit_admin_device_path(@admin_device)
      %br
      = link_to 'Back', admin_devices_path